In [48]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity as cs

# Creating the database with the ratings
user_ratings = pd.DataFrame({'Movie 1':[5.0, 4.0, 3.0, 2.0], 'Movie 2': [3, 2, None, 5],
                             'Movie 3':[None, 1, None, 1], 'Movie 4': [1, None, 1, 5],
                             'Movie 5': [None, None, 3, 3], 'Movie 6': [None, 1, 3, 4]},
                             index = ['User X', 'User Y', 'User Z', 'User W'])
user_ratings

Movie 1  Movie 2  Movie 3  Movie 4  Movie 5  Movie 6
User X      5.0      3.0      NaN      1.0      NaN      NaN
User Y      4.0      2.0      1.0      NaN      NaN      1.0
User Z      3.0      NaN      NaN      1.0      3.0      3.0
User W      2.0      5.0      1.0      5.0      3.0      4.0

In [90]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

A =  np.array([user_ratings.loc['User X'].values,
               user_ratings.loc['User Y'].values,
               user_ratings.loc['User Z'].values,
               user_ratings.loc['User W'].values])
A_sparse = sparse.csr_matrix(A)

similarities = cosine_similarity(A_sparse)
print('pairwise dense output:\n {}\n'.format(similarities))

#also can output sparse matrices
similarities_sparse = cosine_similarity(A_sparse,dense_output=False)
print('pairwise sparse output:\n {}\n'.format(similarities_sparse))

pairwise dense output:
 [[1.         0.93697496 0.51110125 0.56694671]
 [0.93697496 1.         0.60436722 0.54824099]
 [0.51110125 0.60436722 1.         0.6761234 ]
 [0.56694671 0.54824099 0.6761234  1.        ]]

pairwise sparse output:
   (0, 3)	0.5669467095138409
  (0, 2)	0.5111012519999519
  (0, 1)	0.9369749612033813
  (0, 0)	1.0
  (1, 3)	0.5482409888162156
  (1, 2)	0.6043672230190352
  (1, 1)	0.9999999999999998
  (1, 0)	0.9369749612033813
  (2, 3)	0.6761234037828132
  (2, 2)	1.0
  (2, 1)	0.6043672230190352
  (2, 0)	0.5111012519999519
  (3, 3)	1.0000000000000002
  (3, 2)	0.6761234037828132
  (3, 1)	0.5482409888162156
  (3, 0)	0.5669467095138409



In [95]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

A =  np.array([user_ratings.loc['User X'].values,
               user_ratings.loc['User Y'].values,
               user_ratings.loc['User Z'].values,
               user_ratings.loc['User W'].values])
A_sparse = sparse.csr_matrix(A)

similarities = cosine_similarity(A_sparse)
print('cosine similarities table:\n {}\n'.format(similarities))


cosine similarities table:
 [[1.         0.93697496 0.51110125 0.56694671]
 [0.93697496 1.         0.60436722 0.54824099]
 [0.51110125 0.60436722 1.         0.6761234 ]
 [0.56694671 0.54824099 0.6761234  1.        ]]

